# Copy this file as 'local.nix'
# Then uncomment one of the imports

{ ... }:

{
    imports = [
        # ./arkilin => My home PC
        # ./kilin => My laptop
    ];

    home.stateVersion = "20.03"; # Change it by the value generated by home-manager in the default home.nix
}
